services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pokedex:latest
    ports:
      - "8377:8377" 
    env_file:
      - .env
    # command: ["/app/.venv/bin/uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8377"]